modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL v3.0"
[[mods]]
modId="rotp_kw"
version="${file.jarVersion}"
displayName="RotP Kraft Work"
logoFile="logo.png"
credits='''

  Stand sound effects:
    LAMBIRNO - https://www.youtube.com/channel/UCimScfxJm09SNUiWNc0LldQ
  Translation files:
    Chinese Simplified: Hollow Man
'''
authors="DanielGamer321, StandoByte"
description='''
An addon for Ripples of the Past mod, adding a new Stand - Kraft Work.
'''
[[dependencies.rotp_kw]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_kw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_kw]]
    modId="jojo"
    mandatory=true
    versionRange="[0.2.2,0.3)"
    ordering="AFTER"
    side="BOTH"
